// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsqhhZElQ0C6iqzS2xQ3vnsJZxsf8aPBM',
    appId: '1:735454451478:web:6a31c234c591692563e237',
    messagingSenderId: '735454451478',
    projectId: 'exam-64b12',
    authDomain: 'exam-64b12.firebaseapp.com',
    storageBucket: 'exam-64b12.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4rFdk1IZ7SXwFNaTDWduP_ZfMNFA6YL0',
    appId: '1:735454451478:android:864440566561a51d63e237',
    messagingSenderId: '735454451478',
    projectId: 'exam-64b12',
    storageBucket: 'exam-64b12.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvXeLicKENWSM5QDKs2z035vtIDkp1mjM',
    appId: '1:735454451478:ios:4a9f03fe9d795e6a63e237',
    messagingSenderId: '735454451478',
    projectId: 'exam-64b12',
    storageBucket: 'exam-64b12.appspot.com',
    iosBundleId: 'com.example.flutterAdvCh3Exam',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvXeLicKENWSM5QDKs2z035vtIDkp1mjM',
    appId: '1:735454451478:ios:4a9f03fe9d795e6a63e237',
    messagingSenderId: '735454451478',
    projectId: 'exam-64b12',
    storageBucket: 'exam-64b12.appspot.com',
    iosBundleId: 'com.example.flutterAdvCh3Exam',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCsqhhZElQ0C6iqzS2xQ3vnsJZxsf8aPBM',
    appId: '1:735454451478:web:067fae86e733fc8d63e237',
    messagingSenderId: '735454451478',
    projectId: 'exam-64b12',
    authDomain: 'exam-64b12.firebaseapp.com',
    storageBucket: 'exam-64b12.appspot.com',
  );
}
